
import StarvedRockPic from './starved-rock.jpg';
import KennysPic from './Kennys.jpg';
import LunchVisitPic from './lunch-visit.jpg';
import NiagraSmiles2Pic from './niagra-smiles2.jpg';
import SmileAtHomePic from './smile-at-home.jpg';
import BaldKissPic from './bald-kiss.jpg';
import MallGrossFacesPic from './mall-gross-faces.jpg';
import NiagraSmiles3Pic from './niagra-smiles3.jpg';
import CanadaHikeSmilePic from './canada-hike-smile.jpg';
import NapleonDebPic from './napleon-n-deb.jpg';
import NiagraPic from './niagra.jpg';
import SunglassesDumstruckPic from './sunglasses-dumstruck.jpg';
import ChicagoTripPic from './chicago-trip.jpg';
import NerdsSmilePic from './nerds-smile.jpg';
import NotSmileOldPic from './not-smile-old.jpg';
import SunglassesNoSmilePic from './sunglasses-no-smile.jpg';
import DinoPic from './dino.jpg';
import Niagara2Pic from './niagara2.jpg';
import PreWeddingHousePic from './pre-wedding-house.jpg';
import UnderwearHeadsPic from './underwear-heads.jpg';
import LateNightAnniversaryPic from './late-night-anniversary.jpg';
import NiagraKissesPic from './niagra-kisses.jpg';
import SillyEngagementPhotoPic from './silly-engagement-photo.jpg';
import WeirdFacesWmbdPic from './weird-faces-wmbd.jpg';
import LollaPic from './lolla.jpg';
import NiagraSmilesPic from './niagra-smiles.jpg';
import SillySmileysPic from './silly-smileys.jpg';

export const StarvedRock = StarvedRockPic;
export const Kennys = KennysPic;
export const LunchVisit = LunchVisitPic;
export const NiagraSmiles2 = NiagraSmiles2Pic;
export const SmileAtHome = SmileAtHomePic;
export const BaldKiss = BaldKissPic;
export const MallGrossFaces = MallGrossFacesPic;
export const NiagraSmiles3 = NiagraSmiles3Pic;
export const CanadaHikeSmile = CanadaHikeSmilePic;
export const NapleonDeb = NapleonDebPic;
export const Niagra = NiagraPic;
export const SunglassesDumstruck = SunglassesDumstruckPic;
export const ChicagoTrip = ChicagoTripPic;
export const NerdsSmile = NerdsSmilePic;
export const NotSmileOld = NotSmileOldPic;
export const SunglassesNoSmile = SunglassesNoSmilePic;
export const Dino = DinoPic;
export const Niagara2 = Niagara2Pic;
export const PreWeddingHouse = PreWeddingHousePic;
export const UnderwearHeads = UnderwearHeadsPic;
export const LateNightAnniversary = LateNightAnniversaryPic;
export const NiagraKisses = NiagraKissesPic;
export const SillyEngagementPhoto = SillyEngagementPhotoPic;
export const WeirdFacesWmbd = WeirdFacesWmbdPic;
export const Lolla = LollaPic;
export const NiagraSmiles = NiagraSmilesPic;
export const SillySmileys = SillySmileysPic;